INFO: 2020-04-27 10:59:37,920: main() 'Using profile folder /home/hine/.config/variety/'
INFO: 2020-04-27 10:59:37,923: perform_upgrade() 'Last run version was 0.8.3 or earlier, current version is 0.8.3'
INFO: 2020-04-27 10:59:38,061: process_command() 'Received command: []'
INFO: 2020-04-27 10:59:38,063: load_banned() 'Missing or invalid banned URLs list, no URLs will be banned'
INFO: 2020-04-27 10:59:38,082: start() 'Using data_path /usr/share/variety'
INFO: 2020-04-27 10:59:38,082: load() 'Jumble loading'
INFO: 2020-04-27 10:59:38,083: _walk_modules() 'Jumble loading module in __init__ from /usr/lib/python3.8/site-packages/variety/plugins/builtin/__init__.py'
INFO: 2020-04-27 10:59:38,084: _walk_modules() 'Jumble loading module in QuotationsPageSource from /usr/lib/python3.8/site-packages/variety/plugins/builtin/quotes/QuotationsPageSource.py'
INFO: 2020-04-27 10:59:38,089: load() 'Jumble found plugin class: <class 'QuotationsPageSource.QuotationsPageSource'>: {'name': 'TheQuotationsPage.com', 'description': '从 QuotationsPage.com 获取箴言', 'author': 'Peter Levi', 'version': '0.1'}'
INFO: 2020-04-27 10:59:38,090: _walk_modules() 'Jumble loading module in FortuneSource from /usr/lib/python3.8/site-packages/variety/plugins/builtin/quotes/FortuneSource.py'
INFO: 2020-04-27 10:59:38,090: load() 'Jumble found plugin class: <class 'FortuneSource.FortuneSource'>: {'name': 'UNIX fortune program', 'description': 'Displays quotes using the UNIX fortune program. You may want to install additional fortune packs, e.g. fortunes-bofh-excuses.', 'author': 'Dan Jones', 'version': '0.1'}'
INFO: 2020-04-27 10:59:38,090: _walk_modules() 'Jumble loading module in LocalFilesSource from /usr/lib/python3.8/site-packages/variety/plugins/builtin/quotes/LocalFilesSource.py'
INFO: 2020-04-27 10:59:38,091: load() 'Jumble found plugin class: <class 'LocalFilesSource.LocalFilesSource'>: {'name': 'Local text files', 'description': 'Displays quotes, defined in local text files.\nPut your own txt files in: ~/.config/variety/pluginconfig/quotes/.\nThe file format is:\n\nquote -- author\n.\nsecond quote -- another author\n.\netc...\n\nExample: http://rvelthuis.de/zips/quotes.txt', 'author': 'Peter Levi', 'version': '0.1'}'
INFO: 2020-04-27 10:59:38,091: _walk_modules() 'Jumble loading module in GoodreadsSource from /usr/lib/python3.8/site-packages/variety/plugins/builtin/quotes/GoodreadsSource.py'
INFO: 2020-04-27 10:59:38,092: load() 'Jumble found plugin class: <class 'GoodreadsSource.GoodreadsSource'>: {'name': 'Goodreads', 'description': '从 Goodreads.com 获取箴言', 'author': 'Peter Levi', 'version': '0.1'}'
INFO: 2020-04-27 10:59:38,092: _walk_modules() 'Jumble loading module in UrbanDictionarySource from /usr/lib/python3.8/site-packages/variety/plugins/builtin/quotes/UrbanDictionarySource.py'
INFO: 2020-04-27 10:59:38,092: load() 'Jumble found plugin class: <class 'UrbanDictionarySource.UrbanDictionarySource'>: {'name': 'Urban Dictionary', 'description': 'Displays definitions from Urban Dictionary', 'author': 'James Miller', 'version': '0.1'}'
INFO: 2020-04-27 10:59:38,093: _walk_modules() 'Jumble loading module in __init__ from /usr/lib/python3.8/site-packages/variety/plugins/builtin/quotes/__init__.py'
INFO: 2020-04-27 10:59:38,093: _walk_modules() 'Jumble loading module in RedditSource from /usr/lib/python3.8/site-packages/variety/plugins/builtin/downloaders/RedditSource.py'
INFO: 2020-04-27 10:59:38,095: load() 'Jumble found plugin class: <class 'RedditSource.RedditSource'>: {'name': 'RedditSource', 'description': 'Configurable source for fetching images from Reddit', 'author': 'Peter Levi', 'version': '0.1'}'
INFO: 2020-04-27 10:59:38,095: _walk_modules() 'Jumble loading module in WallhavenDownloader from /usr/lib/python3.8/site-packages/variety/plugins/builtin/downloaders/WallhavenDownloader.py'
INFO: 2020-04-27 10:59:38,097: _walk_modules() 'Jumble loading module in APODDownloader from /usr/lib/python3.8/site-packages/variety/plugins/builtin/downloaders/APODDownloader.py'
INFO: 2020-04-27 10:59:38,097: load() 'Jumble found plugin class: <class 'APODDownloader.APODDownloader'>: {'name': 'APODDownloader', 'description': 'NASA Astro Pic of the Day', 'author': 'Peter Levi', 'version': '0.1'}'
INFO: 2020-04-27 10:59:38,098: _walk_modules() 'Jumble loading module in DesktopprDownloader from /usr/lib/python3.8/site-packages/variety/plugins/builtin/downloaders/DesktopprDownloader.py'
INFO: 2020-04-27 10:59:38,099: load() 'Jumble found plugin class: <class 'DesktopprDownloader.DesktopprDownloader'>: {'name': 'DesktopprDownloader', 'description': 'Random wallpapers from Desktoppr.co', 'author': 'Peter Levi', 'version': '0.1'}'
INFO: 2020-04-27 10:59:38,099: _walk_modules() 'Jumble loading module in RedditDownloader from /usr/lib/python3.8/site-packages/variety/plugins/builtin/downloaders/RedditDownloader.py'
INFO: 2020-04-27 10:59:38,099: _walk_modules() 'Jumble loading module in MediaRSSSource from /usr/lib/python3.8/site-packages/variety/plugins/builtin/downloaders/MediaRSSSource.py'
INFO: 2020-04-27 10:59:38,100: load() 'Jumble found plugin class: <class 'MediaRSSSource.MediaRSSSource'>: {'name': 'MediaRSSSource', 'description': 'Configurable source for fetching images from MediaRSS feeds', 'author': 'Peter Levi', 'version': '0.1'}'
INFO: 2020-04-27 10:59:38,101: _walk_modules() 'Jumble loading module in BingDownloader from /usr/lib/python3.8/site-packages/variety/plugins/builtin/downloaders/BingDownloader.py'
INFO: 2020-04-27 10:59:38,101: load() 'Jumble found plugin class: <class 'BingDownloader.BingDownloader'>: {'name': 'BingDownloader', 'description': 'Bing Photo of the Day', 'author': 'Peter Levi', 'version': '0.1'}'
INFO: 2020-04-27 10:59:38,101: _walk_modules() 'Jumble loading module in UnsplashDownloader from /usr/lib/python3.8/site-packages/variety/plugins/builtin/downloaders/UnsplashDownloader.py'
INFO: 2020-04-27 10:59:38,102: load() 'Jumble found plugin class: <class 'UnsplashDownloader.UnsplashDownloader'>: {'name': 'UnsplashDownloader', 'description': 'High-resolution photos from Unsplash.com', 'author': 'Peter Levi', 'version': '0.1'}'
INFO: 2020-04-27 10:59:38,102: _walk_modules() 'Jumble loading module in MediaRSSDownloader from /usr/lib/python3.8/site-packages/variety/plugins/builtin/downloaders/MediaRSSDownloader.py'
INFO: 2020-04-27 10:59:38,103: _walk_modules() 'Jumble loading module in WallhavenSource from /usr/lib/python3.8/site-packages/variety/plugins/builtin/downloaders/WallhavenSource.py'
INFO: 2020-04-27 10:59:38,104: load() 'Jumble found plugin class: <class 'WallhavenSource.WallhavenSource'>: {'name': 'MediaRSSSource', 'description': 'Configurable source for fetching images from Wallhaven.cc', 'author': 'Peter Levi', 'version': '0.1'}'
INFO: 2020-04-27 10:59:38,104: _walk_modules() 'Jumble loading module in EarthviewDownloader from /usr/lib/python3.8/site-packages/variety/plugins/builtin/downloaders/EarthviewDownloader.py'
INFO: 2020-04-27 10:59:38,105: load() 'Jumble found plugin class: <class 'EarthviewDownloader.EarthviewDownloader'>: {'name': 'EarthviewDownloader', 'description': 'Google Earth View Wallpapers', 'author': 'Peter Levi', 'version': '0.1'}'
INFO: 2020-04-27 10:59:38,105: _walk_modules() 'Jumble loading module in ChromeOSWallpapersDownloader from /usr/lib/python3.8/site-packages/variety/plugins/builtin/downloaders/ChromeOSWallpapersDownloader.py'
INFO: 2020-04-27 10:59:38,106: load() 'Jumble found plugin class: <class 'ChromeOSWallpapersDownloader.ChromeOSWallpapersDownloader'>: {'name': 'ChromeOsWallpapersDownloader', 'description': 'Chrome OS Wallpapers', 'author': 'Peter Levi', 'version': '0.1'}'
INFO: 2020-04-27 10:59:38,106: _walk_modules() 'Jumble loading module in UnsplashConfigurableSource from /usr/lib/python3.8/site-packages/variety/plugins/builtin/downloaders/UnsplashConfigurableSource.py'
INFO: 2020-04-27 10:59:38,107: load() 'Jumble found plugin class: <class 'UnsplashConfigurableSource.UnsplashConfigurableSource'>: {'name': 'UnsplashConfigurableSource', 'description': 'Configurable source for fetching photos from Unsplash.com', 'author': 'Peter Levi', 'version': '0.1'}'
INFO: 2020-04-27 10:59:38,107: _walk_modules() 'Jumble loading module in __init__ from /usr/lib/python3.8/site-packages/variety/plugins/builtin/downloaders/__init__.py'
INFO: 2020-04-27 10:59:38,124: reload_config() 'Creating new downloader for type bing, location Bing Photo of the Day'
INFO: 2020-04-27 10:59:38,172: log_options() 'Loaded options:'
INFO: 2020-04-27 10:59:38,172: log_options() 'change_enabled = True'
INFO: 2020-04-27 10:59:38,172: log_options() 'change_interval = 300'
INFO: 2020-04-27 10:59:38,172: log_options() 'change_on_start = False'
INFO: 2020-04-27 10:59:38,172: log_options() 'clipboard_enabled = False'
INFO: 2020-04-27 10:59:38,172: log_options() 'clipboard_hosts = ['wallhaven.cc', 'wallpapers.net', 'flickr.com', 'imgur.com', 'deviantart.com', 'interfacelift.com', 'vladstudio.com', 'imageshack.us', 'deviantart.net', 'imageshack.com']'
INFO: 2020-04-27 10:59:38,172: log_options() 'clipboard_use_whitelist = True'
INFO: 2020-04-27 10:59:38,172: log_options() 'clock_date_font = Ubuntu Condensed, 30'
INFO: 2020-04-27 10:59:38,172: log_options() 'clock_enabled = False'
INFO: 2020-04-27 10:59:38,172: log_options() 'clock_filter = -density 100 -font `fc-match -f '%{file[0]}' '%CLOCK_FONT_NAME'` -pointsize %CLOCK_FONT_SIZE -gravity SouthEast -fill '#00000044' -annotate 0x0+[%HOFFSET+58]+[%VOFFSET+108] '%H:%M' -fill white -annotate 0x0+[%HOFFSET+60]+[%VOFFSET+110] '%H:%M' -font `fc-match -f '%{file[0]}' '%DATE_FONT_NAME'` -pointsize %DATE_FONT_SIZE -fill '#00000044' -annotate 0x0+[%HOFFSET+58]+[%VOFFSET+58] '%A, %B %d' -fill white -annotate 0x0+[%HOFFSET+60]+[%VOFFSET+60] '%A, %B %d''
INFO: 2020-04-27 10:59:38,172: log_options() 'clock_font = Ubuntu Condensed, 70'
INFO: 2020-04-27 10:59:38,172: log_options() 'configfile = /home/hine/.config/variety/variety.conf'
INFO: 2020-04-27 10:59:38,173: log_options() 'copyto_enabled = False'
INFO: 2020-04-27 10:59:38,173: log_options() 'copyto_folder = Default'
INFO: 2020-04-27 10:59:38,173: log_options() 'desired_color = [160, 160, 160]'
INFO: 2020-04-27 10:59:38,173: log_options() 'desired_color_enabled = False'
INFO: 2020-04-27 10:59:38,173: log_options() 'download_folder = /home/hine/.config/variety/Downloaded'
INFO: 2020-04-27 10:59:38,173: log_options() 'download_preference_ratio = 0.9'
INFO: 2020-04-27 10:59:38,173: log_options() 'favorites_folder = /home/hine/.config/variety/Favorites'
INFO: 2020-04-27 10:59:38,173: log_options() 'favorites_operations = [['Downloaded', 'Copy'], ['Fetched', 'Move'], ['Others', 'Copy']]'
INFO: 2020-04-27 10:59:38,173: log_options() 'fetched_folder = /home/hine/.config/variety/Fetched'
INFO: 2020-04-27 10:59:38,173: log_options() 'filters = [[False, 'Keep original', ''], [False, 'Grayscale', '-type Grayscale'], [False, 'Heavy blur', '-blur 120x40'], [False, 'Soft blur', '-blur 20x7'], [False, 'Oil painting', '-paint 8'], [False, 'Pointilism', '-spread 10 -noise 3'], [False, 'Pixellate', '-scale 3% -scale 3333%']]'
INFO: 2020-04-27 10:59:38,173: log_options() 'icon = Light'
INFO: 2020-04-27 10:59:38,173: log_options() 'lightness_enabled = False'
INFO: 2020-04-27 10:59:38,173: log_options() 'lightness_mode = 0'
INFO: 2020-04-27 10:59:38,173: log_options() 'min_rating = 4'
INFO: 2020-04-27 10:59:38,173: log_options() 'min_rating_enabled = False'
INFO: 2020-04-27 10:59:38,173: log_options() 'min_size = 80'
INFO: 2020-04-27 10:59:38,173: log_options() 'min_size_enabled = False'
INFO: 2020-04-27 10:59:38,173: log_options() 'quota_enabled = True'
INFO: 2020-04-27 10:59:38,173: log_options() 'quota_size = 1000'
INFO: 2020-04-27 10:59:38,173: log_options() 'quotes_authors = '
INFO: 2020-04-27 10:59:38,173: log_options() 'quotes_bg_color = [80, 80, 80]'
INFO: 2020-04-27 10:59:38,173: log_options() 'quotes_bg_opacity = 55'
INFO: 2020-04-27 10:59:38,173: log_options() 'quotes_change_enabled = False'
INFO: 2020-04-27 10:59:38,173: log_options() 'quotes_change_interval = 300'
INFO: 2020-04-27 10:59:38,173: log_options() 'quotes_disabled_sources = ['Urban Dictionary']'
INFO: 2020-04-27 10:59:38,173: log_options() 'quotes_enabled = False'
INFO: 2020-04-27 10:59:38,173: log_options() 'quotes_favorites_file = /home/hine/.config/variety/favorite_quotes.txt'
INFO: 2020-04-27 10:59:38,173: log_options() 'quotes_font = Bitstream Charter 30'
INFO: 2020-04-27 10:59:38,173: log_options() 'quotes_hpos = 100'
INFO: 2020-04-27 10:59:38,173: log_options() 'quotes_max_length = 250'
INFO: 2020-04-27 10:59:38,173: log_options() 'quotes_tags = '
INFO: 2020-04-27 10:59:38,173: log_options() 'quotes_text_color = [255, 255, 255]'
INFO: 2020-04-27 10:59:38,173: log_options() 'quotes_text_shadow = False'
INFO: 2020-04-27 10:59:38,174: log_options() 'quotes_vpos = 40'
INFO: 2020-04-27 10:59:38,174: log_options() 'quotes_width = 70'
INFO: 2020-04-27 10:59:38,174: log_options() 'safe_mode = False'
INFO: 2020-04-27 10:59:38,174: log_options() 'slideshow_custom_enabled = False'
INFO: 2020-04-27 10:59:38,174: log_options() 'slideshow_custom_folder = /home/hine/图片'
INFO: 2020-04-27 10:59:38,174: log_options() 'slideshow_downloads_enabled = False'
INFO: 2020-04-27 10:59:38,174: log_options() 'slideshow_fade = 0.4'
INFO: 2020-04-27 10:59:38,174: log_options() 'slideshow_favorites_enabled = True'
INFO: 2020-04-27 10:59:38,174: log_options() 'slideshow_mode = Fullscreen'
INFO: 2020-04-27 10:59:38,174: log_options() 'slideshow_monitor = All'
INFO: 2020-04-27 10:59:38,174: log_options() 'slideshow_pan = 0.05'
INFO: 2020-04-27 10:59:38,174: log_options() 'slideshow_seconds = 6.0'
INFO: 2020-04-27 10:59:38,174: log_options() 'slideshow_sort_order = Random'
INFO: 2020-04-27 10:59:38,174: log_options() 'slideshow_sources_enabled = True'
INFO: 2020-04-27 10:59:38,174: log_options() 'slideshow_zoom = 0.2'
INFO: 2020-04-27 10:59:38,174: log_options() 'smart_enabled = False'
INFO: 2020-04-27 10:59:38,174: log_options() 'smart_notice_shown = False'
INFO: 2020-04-27 10:59:38,174: log_options() 'smart_register_shown = False'
INFO: 2020-04-27 10:59:38,174: log_options() 'sources = [[False, 'favorites', 'The Favorites folder'], [False, 'fetched', 'The Fetched folder'], [False, 'folder', '/usr/share/backgrounds'], [False, 'flickr', 'user:www.flickr.com/photos/peter-levi/;user_id:93647178@N00;'], [False, 'apod', "NASA's Astronomy Picture of the Day"], [True, 'bing', 'Bing Photo of the Day'], [False, 'chromeos', 'Chrome OS Wallpapers'], [False, 'earthview', 'Google Earth View Wallpapers'], [False, 'desktoppr', 'Random wallpapers from Desktoppr.co'], [False, 'unsplash', 'High-resolution photos from Unsplash.com'], [True, 'folder', '/home/hine/图片/Zoe']]'
INFO: 2020-04-27 10:59:38,174: log_options() 'stats_enabled = True'
INFO: 2020-04-27 10:59:38,174: log_options() 'stats_notice_shown = False'
INFO: 2020-04-27 10:59:38,174: log_options() 'sync_enabled = True'
INFO: 2020-04-27 10:59:38,174: log_options() 'use_landscape_enabled = True'
INFO: 2020-04-27 10:59:38,174: reload_config() 'No need to clear prepared queue'
INFO: 2020-04-27 10:59:38,174: update_indicator() 'Setting file info to: /home/hine/.config/variety/Downloaded/Bing/OHR.NeistPoint_ZH-CN3115403132_1920x1080.jpg'
INFO: 2020-04-27 10:59:38,231: load_last_change_time() 'Change interval < 6 hours, ignore persisted last_change_time, wait initially the whole interval: 300'
INFO: 2020-04-27 10:59:38,232: update_indicator() 'Setting file info to: /home/hine/.config/variety/Downloaded/Bing/OHR.NeistPoint_ZH-CN3115403132_1920x1080.jpg'
INFO: 2020-04-27 10:59:38,234: regular_change_thread() 'regular_change thread running'
INFO: 2020-04-27 10:59:38,235: prepare_thread() 'Prepare thread running'
INFO: 2020-04-27 10:59:38,235: prepare_thread() 'Prepared buffer contains 0 images'
INFO: 2020-04-27 10:59:38,235: prepare_thread() 'Preparing some images'
INFO: 2020-04-27 10:59:38,236: get_throttling() 'Bing: parsing serverside options'
INFO: 2020-04-27 10:59:38,236: get_throttling() 'Could not parse Bing serverside options, using defaults None, None'
INFO: 2020-04-27 10:59:38,236: get_throttling() 'Bing: parsing serverside options'
INFO: 2020-04-27 10:59:38,237: get_throttling() 'Could not parse Bing serverside options, using defaults None, None'
INFO: 2020-04-27 10:59:38,237: download_one() 'Bing: Downloading an image, config: None'
INFO: 2020-04-27 10:59:38,237: download_one() 'Bing: Queue size: 0'
INFO: 2020-04-27 10:59:38,237: get_throttling() 'Bing: parsing serverside options'
INFO: 2020-04-27 10:59:38,237: get_throttling() 'Could not parse Bing serverside options, using defaults None, None'
INFO: 2020-04-27 10:59:38,237: download_one() 'Bing: Filling queue'
INFO: 2020-04-27 10:59:38,244: update_indicator_icon() 'Creating indicator'
ERROR: 2020-04-27 10:59:38,271: download_one_from() 'Could not download wallpaper:'
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/urllib3/connection.py", line 159, in _new_conn
    conn = connection.create_connection(
  File "/usr/lib/python3.8/site-packages/urllib3/util/connection.py", line 61, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "/usr/lib/python3.8/socket.py", line 918, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -2] 未知的名称或服务

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/urllib3/connectionpool.py", line 670, in urlopen
    httplib_response = self._make_request(
  File "/usr/lib/python3.8/site-packages/urllib3/connectionpool.py", line 381, in _make_request
    self._validate_conn(conn)
  File "/usr/lib/python3.8/site-packages/urllib3/connectionpool.py", line 976, in _validate_conn
    conn.connect()
  File "/usr/lib/python3.8/site-packages/urllib3/connection.py", line 308, in connect
    conn = self._new_conn()
  File "/usr/lib/python3.8/site-packages/urllib3/connection.py", line 171, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x7fb6a446f640>: Failed to establish a new connection: [Errno -2] 未知的名称或服务

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/usr/lib/python3.8/site-packages/urllib3/connectionpool.py", line 724, in urlopen
    retries = retries.increment(
  File "/usr/lib/python3.8/site-packages/urllib3/util/retry.py", line 439, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='www.bing.com', port=443): Max retries exceeded with url: /HPImageArchive.aspx?format=js&idx=0&n=100&mkt=en-US (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fb6a446f640>: Failed to establish a new connection: [Errno -2] 未知的名称或服务'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/variety/VarietyWindow.py", line 1159, in download_one_from
    file = downloader.download_one()
  File "/usr/lib/python3.8/site-packages/variety/plugins/downloaders/DefaultDownloader.py", line 141, in download_one
    items = self.fill_queue()
  File "/usr/lib/python3.8/site-packages/variety/plugins/builtin/downloaders/BingDownloader.py", line 61, in fill_queue
    s = Util.fetch_json(BingDownloader.BING_JSON_URL)
  File "/usr/lib/python3.8/site-packages/variety/Util.py", line 643, in fetch_json
    return Util.request(url, data, **request_kwargs).json()
  File "/usr/lib/python3.8/site-packages/variety/Util.py", line 612, in request
    r = requests.request(
  File "/usr/lib/python3.8/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python3.8/site-packages/requests/sessions.py", line 530, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3.8/site-packages/requests/sessions.py", line 643, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3.8/site-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='www.bing.com', port=443): Max retries exceeded with url: /HPImageArchive.aspx?format=js&idx=0&n=100&mkt=en-US (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fb6a446f640>: Failed to establish a new connection: [Errno -2] 未知的名称或服务'))
WARNING: 2020-04-27 10:59:38,298: create_menu() 'Variety Slideshow is not installed. This is an optional extension adding pan-and-zoom slideshows to Variety: see https://github.com/peterlevi/variety-slideshow for details'
INFO: 2020-04-27 10:59:38,304: create_indicator() 'indicator backend: AppIndicator3'
INFO: 2020-04-27 10:59:38,332: do_set_wp() 'Calling do_set_wp with /home/hine/.config/variety/Downloaded/Bing/OHR.NeistPoint_ZH-CN3115403132_1920x1080.jpg, time: 1587956378.3321774'
INFO: 2020-04-27 10:59:38,353: set_from_theme_icon() 'Showing indicator icon variety-indicator from GTK theme'
INFO: 2020-04-27 10:59:38,358: update_indicator() 'Setting file info to: /home/hine/.config/variety/Downloaded/Bing/OHR.NeistPoint_ZH-CN3115403132_1920x1080.jpg'
INFO: 2020-04-27 10:59:38,362: list_files() 'More than 1 files in the folders, stop listing'
INFO: 2020-04-27 10:59:38,460: prepare_thread() 'After search prepared buffer contains 53 images'
INFO: 2020-04-27 10:59:39,763: reload() 'Reloading preferences dialog'
INFO: 2020-04-27 10:59:40,465: trigger_download() 'Triggering download thread to check if download needed'
INFO: 2020-04-27 10:59:58,259: server_options_thread() 'Fetching server options from http://tiny.cc/variety-options-063'
ERROR: 2020-04-27 11:00:03,282: server_options_thread() 'Could not fetch Variety serverside options'
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/urllib3/connection.py", line 159, in _new_conn
    conn = connection.create_connection(
  File "/usr/lib/python3.8/site-packages/urllib3/util/connection.py", line 84, in create_connection
    raise err
  File "/usr/lib/python3.8/site-packages/urllib3/util/connection.py", line 74, in create_connection
    sock.connect(sa)
socket.timeout: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/urllib3/connectionpool.py", line 670, in urlopen
    httplib_response = self._make_request(
  File "/usr/lib/python3.8/site-packages/urllib3/connectionpool.py", line 392, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/lib/python3.8/http/client.py", line 1230, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib/python3.8/http/client.py", line 1276, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.8/http/client.py", line 1225, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.8/http/client.py", line 1004, in _send_output
    self.send(msg)
  File "/usr/lib/python3.8/http/client.py", line 944, in send
    self.connect()
  File "/usr/lib/python3.8/site-packages/urllib3/connection.py", line 187, in connect
    conn = self._new_conn()
  File "/usr/lib/python3.8/site-packages/urllib3/connection.py", line 164, in _new_conn
    raise ConnectTimeoutError(
urllib3.exceptions.ConnectTimeoutError: (<urllib3.connection.HTTPConnection object at 0x7fb6a41e18e0>, 'Connection to tiny.cc timed out. (connect timeout=5)')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/usr/lib/python3.8/site-packages/urllib3/connectionpool.py", line 724, in urlopen
    retries = retries.increment(
  File "/usr/lib/python3.8/site-packages/urllib3/util/retry.py", line 439, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='tiny.cc', port=80): Max retries exceeded with url: /variety-options-063 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fb6a41e18e0>, 'Connection to tiny.cc timed out. (connect timeout=5)'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/variety/VarietyWindow.py", line 1087, in server_options_thread
    self.server_options = Util.fetch_json(VarietyWindow.SERVERSIDE_OPTIONS_URL)
  File "/usr/lib/python3.8/site-packages/variety/Util.py", line 643, in fetch_json
    return Util.request(url, data, **request_kwargs).json()
  File "/usr/lib/python3.8/site-packages/variety/Util.py", line 612, in request
    r = requests.request(
  File "/usr/lib/python3.8/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python3.8/site-packages/requests/sessions.py", line 530, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3.8/site-packages/requests/sessions.py", line 643, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3.8/site-packages/requests/adapters.py", line 504, in send
    raise ConnectTimeout(e, request=request)
requests.exceptions.ConnectTimeout: HTTPConnectionPool(host='tiny.cc', port=80): Max retries exceeded with url: /variety-options-063 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fb6a41e18e0>, 'Connection to tiny.cc timed out. (connect timeout=5)'))
INFO: 2020-04-27 11:00:33,289: server_options_thread() 'Fetching server options from http://tiny.cc/variety-options-063'
ERROR: 2020-04-27 11:00:38,316: server_options_thread() 'Could not fetch Variety serverside options'
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/urllib3/connection.py", line 159, in _new_conn
    conn = connection.create_connection(
  File "/usr/lib/python3.8/site-packages/urllib3/util/connection.py", line 84, in create_connection
    raise err
  File "/usr/lib/python3.8/site-packages/urllib3/util/connection.py", line 74, in create_connection
    sock.connect(sa)
socket.timeout: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/urllib3/connectionpool.py", line 670, in urlopen
    httplib_response = self._make_request(
  File "/usr/lib/python3.8/site-packages/urllib3/connectionpool.py", line 392, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/lib/python3.8/http/client.py", line 1230, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib/python3.8/http/client.py", line 1276, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.8/http/client.py", line 1225, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.8/http/client.py", line 1004, in _send_output
    self.send(msg)
  File "/usr/lib/python3.8/http/client.py", line 944, in send
    self.connect()
  File "/usr/lib/python3.8/site-packages/urllib3/connection.py", line 187, in connect
    conn = self._new_conn()
  File "/usr/lib/python3.8/site-packages/urllib3/connection.py", line 164, in _new_conn
    raise ConnectTimeoutError(
urllib3.exceptions.ConnectTimeoutError: (<urllib3.connection.HTTPConnection object at 0x7fb67ce1e5e0>, 'Connection to tiny.cc timed out. (connect timeout=5)')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/usr/lib/python3.8/site-packages/urllib3/connectionpool.py", line 724, in urlopen
    retries = retries.increment(
  File "/usr/lib/python3.8/site-packages/urllib3/util/retry.py", line 439, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='tiny.cc', port=80): Max retries exceeded with url: /variety-options-063 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fb67ce1e5e0>, 'Connection to tiny.cc timed out. (connect timeout=5)'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/variety/VarietyWindow.py", line 1087, in server_options_thread
    self.server_options = Util.fetch_json(VarietyWindow.SERVERSIDE_OPTIONS_URL)
  File "/usr/lib/python3.8/site-packages/variety/Util.py", line 643, in fetch_json
    return Util.request(url, data, **request_kwargs).json()
  File "/usr/lib/python3.8/site-packages/variety/Util.py", line 612, in request
    r = requests.request(
  File "/usr/lib/python3.8/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python3.8/site-packages/requests/sessions.py", line 530, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3.8/site-packages/requests/sessions.py", line 643, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3.8/site-packages/requests/adapters.py", line 504, in send
    raise ConnectTimeout(e, request=request)
requests.exceptions.ConnectTimeout: HTTPConnectionPool(host='tiny.cc', port=80): Max retries exceeded with url: /variety-options-063 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fb67ce1e5e0>, 'Connection to tiny.cc timed out. (connect timeout=5)'))
INFO: 2020-04-27 11:01:08,345: server_options_thread() 'Fetching server options from http://tiny.cc/variety-options-063'
ERROR: 2020-04-27 11:01:13,401: server_options_thread() 'Could not fetch Variety serverside options'
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/urllib3/connection.py", line 159, in _new_conn
    conn = connection.create_connection(
  File "/usr/lib/python3.8/site-packages/urllib3/util/connection.py", line 84, in create_connection
    raise err
  File "/usr/lib/python3.8/site-packages/urllib3/util/connection.py", line 74, in create_connection
    sock.connect(sa)
socket.timeout: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/urllib3/connectionpool.py", line 670, in urlopen
    httplib_response = self._make_request(
  File "/usr/lib/python3.8/site-packages/urllib3/connectionpool.py", line 392, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/lib/python3.8/http/client.py", line 1230, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib/python3.8/http/client.py", line 1276, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.8/http/client.py", line 1225, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.8/http/client.py", line 1004, in _send_output
    self.send(msg)
  File "/usr/lib/python3.8/http/client.py", line 944, in send
    self.connect()
  File "/usr/lib/python3.8/site-packages/urllib3/connection.py", line 187, in connect
    conn = self._new_conn()
  File "/usr/lib/python3.8/site-packages/urllib3/connection.py", line 164, in _new_conn
    raise ConnectTimeoutError(
urllib3.exceptions.ConnectTimeoutError: (<urllib3.connection.HTTPConnection object at 0x7fb67ce1edc0>, 'Connection to tiny.cc timed out. (connect timeout=5)')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/usr/lib/python3.8/site-packages/urllib3/connectionpool.py", line 724, in urlopen
    retries = retries.increment(
  File "/usr/lib/python3.8/site-packages/urllib3/util/retry.py", line 439, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='tiny.cc', port=80): Max retries exceeded with url: /variety-options-063 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fb67ce1edc0>, 'Connection to tiny.cc timed out. (connect timeout=5)'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/variety/VarietyWindow.py", line 1087, in server_options_thread
    self.server_options = Util.fetch_json(VarietyWindow.SERVERSIDE_OPTIONS_URL)
  File "/usr/lib/python3.8/site-packages/variety/Util.py", line 643, in fetch_json
    return Util.request(url, data, **request_kwargs).json()
  File "/usr/lib/python3.8/site-packages/variety/Util.py", line 612, in request
    r = requests.request(
  File "/usr/lib/python3.8/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python3.8/site-packages/requests/sessions.py", line 530, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3.8/site-packages/requests/sessions.py", line 643, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3.8/site-packages/requests/adapters.py", line 504, in send
    raise ConnectTimeout(e, request=request)
requests.exceptions.ConnectTimeout: HTTPConnectionPool(host='tiny.cc', port=80): Max retries exceeded with url: /variety-options-063 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fb67ce1edc0>, 'Connection to tiny.cc timed out. (connect timeout=5)'))
INFO: 2020-04-27 11:01:43,475: server_options_thread() 'Fetching server options from http://tiny.cc/variety-options-063'
ERROR: 2020-04-27 11:01:48,501: server_options_thread() 'Could not fetch Variety serverside options'
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/urllib3/connection.py", line 159, in _new_conn
    conn = connection.create_connection(
  File "/usr/lib/python3.8/site-packages/urllib3/util/connection.py", line 84, in create_connection
    raise err
  File "/usr/lib/python3.8/site-packages/urllib3/util/connection.py", line 74, in create_connection
    sock.connect(sa)
socket.timeout: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/urllib3/connectionpool.py", line 670, in urlopen
    httplib_response = self._make_request(
  File "/usr/lib/python3.8/site-packages/urllib3/connectionpool.py", line 392, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/lib/python3.8/http/client.py", line 1230, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib/python3.8/http/client.py", line 1276, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.8/http/client.py", line 1225, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.8/http/client.py", line 1004, in _send_output
    self.send(msg)
  File "/usr/lib/python3.8/http/client.py", line 944, in send
    self.connect()
  File "/usr/lib/python3.8/site-packages/urllib3/connection.py", line 187, in connect
    conn = self._new_conn()
  File "/usr/lib/python3.8/site-packages/urllib3/connection.py", line 164, in _new_conn
    raise ConnectTimeoutError(
urllib3.exceptions.ConnectTimeoutError: (<urllib3.connection.HTTPConnection object at 0x7fb67cea55e0>, 'Connection to tiny.cc timed out. (connect timeout=5)')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/usr/lib/python3.8/site-packages/urllib3/connectionpool.py", line 724, in urlopen
    retries = retries.increment(
  File "/usr/lib/python3.8/site-packages/urllib3/util/retry.py", line 439, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='tiny.cc', port=80): Max retries exceeded with url: /variety-options-063 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fb67cea55e0>, 'Connection to tiny.cc timed out. (connect timeout=5)'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/variety/VarietyWindow.py", line 1087, in server_options_thread
    self.server_options = Util.fetch_json(VarietyWindow.SERVERSIDE_OPTIONS_URL)
  File "/usr/lib/python3.8/site-packages/variety/Util.py", line 643, in fetch_json
    return Util.request(url, data, **request_kwargs).json()
  File "/usr/lib/python3.8/site-packages/variety/Util.py", line 612, in request
    r = requests.request(
  File "/usr/lib/python3.8/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python3.8/site-packages/requests/sessions.py", line 530, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3.8/site-packages/requests/sessions.py", line 643, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3.8/site-packages/requests/adapters.py", line 504, in send
    raise ConnectTimeout(e, request=request)
requests.exceptions.ConnectTimeout: HTTPConnectionPool(host='tiny.cc', port=80): Max retries exceeded with url: /variety-options-063 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fb67cea55e0>, 'Connection to tiny.cc timed out. (connect timeout=5)'))
INFO: 2020-04-27 11:02:18,505: server_options_thread() 'Fetching server options from http://tiny.cc/variety-options-063'
ERROR: 2020-04-27 11:02:23,543: server_options_thread() 'Could not fetch Variety serverside options'
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/urllib3/connection.py", line 159, in _new_conn
    conn = connection.create_connection(
  File "/usr/lib/python3.8/site-packages/urllib3/util/connection.py", line 84, in create_connection
    raise err
  File "/usr/lib/python3.8/site-packages/urllib3/util/connection.py", line 74, in create_connection
    sock.connect(sa)
socket.timeout: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/urllib3/connectionpool.py", line 670, in urlopen
    httplib_response = self._make_request(
  File "/usr/lib/python3.8/site-packages/urllib3/connectionpool.py", line 392, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/lib/python3.8/http/client.py", line 1230, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib/python3.8/http/client.py", line 1276, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.8/http/client.py", line 1225, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.8/http/client.py", line 1004, in _send_output
    self.send(msg)
  File "/usr/lib/python3.8/http/client.py", line 944, in send
    self.connect()
  File "/usr/lib/python3.8/site-packages/urllib3/connection.py", line 187, in connect
    conn = self._new_conn()
  File "/usr/lib/python3.8/site-packages/urllib3/connection.py", line 164, in _new_conn
    raise ConnectTimeoutError(
urllib3.exceptions.ConnectTimeoutError: (<urllib3.connection.HTTPConnection object at 0x7fb67ce1e5e0>, 'Connection to tiny.cc timed out. (connect timeout=5)')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/usr/lib/python3.8/site-packages/urllib3/connectionpool.py", line 724, in urlopen
    retries = retries.increment(
  File "/usr/lib/python3.8/site-packages/urllib3/util/retry.py", line 439, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='tiny.cc', port=80): Max retries exceeded with url: /variety-options-063 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fb67ce1e5e0>, 'Connection to tiny.cc timed out. (connect timeout=5)'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/variety/VarietyWindow.py", line 1087, in server_options_thread
    self.server_options = Util.fetch_json(VarietyWindow.SERVERSIDE_OPTIONS_URL)
  File "/usr/lib/python3.8/site-packages/variety/Util.py", line 643, in fetch_json
    return Util.request(url, data, **request_kwargs).json()
  File "/usr/lib/python3.8/site-packages/variety/Util.py", line 612, in request
    r = requests.request(
  File "/usr/lib/python3.8/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python3.8/site-packages/requests/sessions.py", line 530, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3.8/site-packages/requests/sessions.py", line 643, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3.8/site-packages/requests/adapters.py", line 504, in send
    raise ConnectTimeout(e, request=request)
requests.exceptions.ConnectTimeout: HTTPConnectionPool(host='tiny.cc', port=80): Max retries exceeded with url: /variety-options-063 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fb67ce1e5e0>, 'Connection to tiny.cc timed out. (connect timeout=5)'))
INFO: 2020-04-27 11:02:40,466: get_throttling() 'Bing: parsing serverside options'
INFO: 2020-04-27 11:02:40,467: get_throttling() 'Could not parse Bing serverside options, using defaults None, None'
INFO: 2020-04-27 11:02:40,467: get_throttling() 'Bing: parsing serverside options'
INFO: 2020-04-27 11:02:40,467: get_throttling() 'Could not parse Bing serverside options, using defaults None, None'
INFO: 2020-04-27 11:02:40,467: download_one() 'Bing: Downloading an image, config: None'
INFO: 2020-04-27 11:02:40,467: download_one() 'Bing: Queue size: 0'
INFO: 2020-04-27 11:02:40,467: get_throttling() 'Bing: parsing serverside options'
INFO: 2020-04-27 11:02:40,467: get_throttling() 'Could not parse Bing serverside options, using defaults None, None'
INFO: 2020-04-27 11:02:40,467: download_one() 'Bing: Filling queue'
INFO: 2020-04-27 11:02:40,988: download_one() 'Bing: Queue populated with 8 URLs'
INFO: 2020-04-27 11:02:40,988: save_locally() 'Origin URL: https://www.bing.com/search?q=%E8%B7%B3%E5%B2%A9%E4%BC%81%E9%B9%85&form=hpcapt&mkt=zh-cn'
INFO: 2020-04-27 11:02:40,988: save_locally() 'Image URL: https://www.bing.com/th?id=OHR.FalklandRockhoppers_ZH-CN5370686595_1920x1080.jpg&rf=LaDigue_1920x1080.jpg&pid=hp'
INFO: 2020-04-27 11:02:40,988: save_locally() 'Local path: /home/hine/.config/variety/Downloaded/Bing/OHR.FalklandRockhoppers_ZH-CN5370686595_1920x1080.jpg'
INFO: 2020-04-27 11:02:40,988: save_locally() 'File already exists, skip downloading'
INFO: 2020-04-27 11:04:38,232: regular_change_thread() 'regular_change changes wallpaper'
INFO: 2020-04-27 11:04:38,232: set_wallpaper() 'Calling set_wallpaper with /home/hine/.config/variety/Downloaded/Bing/OHR.CharlestonAzaleas_ZH-CN3924268565_1920x1080.jpg'
INFO: 2020-04-27 11:04:38,233: do_set_wp() 'Calling do_set_wp with /home/hine/.config/variety/Downloaded/Bing/OHR.CharlestonAzaleas_ZH-CN3924268565_1920x1080.jpg, time: 1587956678.233173'
INFO: 2020-04-27 11:04:38,233: prepare_thread() 'Prepared buffer contains 52 images'
INFO: 2020-04-27 11:04:38,264: update_indicator() 'Setting file info to: /home/hine/.config/variety/Downloaded/Bing/OHR.CharlestonAzaleas_ZH-CN3924268565_1920x1080.jpg'
INFO: 2020-04-27 11:04:38,268: list_files() 'More than 1 files in the folders, stop listing'
INFO: 2020-04-27 11:04:40,234: trigger_download() 'Triggering download thread to check if download needed'
INFO: 2020-04-27 11:04:40,235: get_throttling() 'Bing: parsing serverside options'
INFO: 2020-04-27 11:04:40,235: get_throttling() 'Could not parse Bing serverside options, using defaults None, None'
INFO: 2020-04-27 11:04:40,236: get_throttling() 'Bing: parsing serverside options'
INFO: 2020-04-27 11:04:40,236: get_throttling() 'Could not parse Bing serverside options, using defaults None, None'
INFO: 2020-04-27 11:04:40,236: download_one() 'Bing: Downloading an image, config: None'
INFO: 2020-04-27 11:04:40,236: download_one() 'Bing: Queue size: 7'
INFO: 2020-04-27 11:04:40,236: download_one() 'Bing: Queue populated with 7 URLs'
INFO: 2020-04-27 11:04:40,237: save_locally() 'Origin URL: https://www.bing.com/search?q=%E7%BB%92%E9%B8%AD&form=hpcapt&mkt=zh-cn'
INFO: 2020-04-27 11:04:40,237: save_locally() 'Image URL: https://www.bing.com/th?id=OHR.KingEider_ZH-CN3559595357_1920x1080.jpg&rf=LaDigue_1920x1080.jpg&pid=hp'
INFO: 2020-04-27 11:04:40,237: save_locally() 'Local path: /home/hine/.config/variety/Downloaded/Bing/OHR.KingEider_ZH-CN3559595357_1920x1080.jpg'
INFO: 2020-04-27 11:04:40,237: save_locally() 'File already exists, skip downloading'
INFO: 2020-04-27 11:07:41,239: get_throttling() 'Bing: parsing serverside options'
INFO: 2020-04-27 11:07:41,239: get_throttling() 'Could not parse Bing serverside options, using defaults None, None'
INFO: 2020-04-27 11:07:41,239: get_throttling() 'Bing: parsing serverside options'
INFO: 2020-04-27 11:07:41,240: get_throttling() 'Could not parse Bing serverside options, using defaults None, None'
INFO: 2020-04-27 11:07:41,240: download_one() 'Bing: Downloading an image, config: None'
INFO: 2020-04-27 11:07:41,240: download_one() 'Bing: Queue size: 6'
INFO: 2020-04-27 11:07:41,240: download_one() 'Bing: Queue populated with 6 URLs'
INFO: 2020-04-27 11:07:41,240: save_locally() 'Origin URL: https://www.bing.com/search?q=%E5%8D%97%E7%BE%8E%E8%B2%98&form=hpcapt&mkt=zh-cn'
INFO: 2020-04-27 11:07:41,240: save_locally() 'Image URL: https://www.bing.com/th?id=OHR.SouthAmericanTapir_ZH-CN6151058361_1920x1080.jpg&rf=LaDigue_1920x1080.jpg&pid=hp'
INFO: 2020-04-27 11:07:41,240: save_locally() 'Local path: /home/hine/.config/variety/Downloaded/Bing/OHR.SouthAmericanTapir_ZH-CN6151058361_1920x1080.jpg'
INFO: 2020-04-27 11:07:41,240: save_locally() 'File already exists, skip downloading'
INFO: 2020-04-27 11:09:38,767: regular_change_thread() 'regular_change changes wallpaper'
INFO: 2020-04-27 11:09:38,768: set_wallpaper() 'Calling set_wallpaper with /home/hine/.config/variety/Downloaded/Bing/OHR.GPS_ZH-CN5160095061_1920x1080.jpg'
INFO: 2020-04-27 11:09:38,769: do_set_wp() 'Calling do_set_wp with /home/hine/.config/variety/Downloaded/Bing/OHR.GPS_ZH-CN5160095061_1920x1080.jpg, time: 1587956978.769126'
INFO: 2020-04-27 11:09:38,769: prepare_thread() 'Prepared buffer contains 51 images'
INFO: 2020-04-27 11:09:38,786: update_indicator() 'Setting file info to: /home/hine/.config/variety/Downloaded/Bing/OHR.GPS_ZH-CN5160095061_1920x1080.jpg'
INFO: 2020-04-27 11:09:38,787: list_files() 'More than 1 files in the folders, stop listing'
INFO: 2020-04-27 11:09:40,770: trigger_download() 'Triggering download thread to check if download needed'
INFO: 2020-04-27 11:09:40,771: get_throttling() 'Bing: parsing serverside options'
INFO: 2020-04-27 11:09:40,771: get_throttling() 'Could not parse Bing serverside options, using defaults None, None'
INFO: 2020-04-27 11:09:40,772: get_throttling() 'Bing: parsing serverside options'
INFO: 2020-04-27 11:09:40,772: get_throttling() 'Could not parse Bing serverside options, using defaults None, None'
INFO: 2020-04-27 11:09:40,772: download_one() 'Bing: Downloading an image, config: None'
INFO: 2020-04-27 11:09:40,772: download_one() 'Bing: Queue size: 5'
INFO: 2020-04-27 11:09:40,772: download_one() 'Bing: Queue populated with 5 URLs'
INFO: 2020-04-27 11:09:40,773: save_locally() 'Origin URL: https://www.bing.com/search?q=%E5%A4%A7%E9%BA%A6%E5%93%B2%E4%BC%A6%E6%98%9F%E4%BA%91&form=hpcapt&mkt=zh-cn'
INFO: 2020-04-27 11:09:40,773: save_locally() 'Image URL: https://www.bing.com/th?id=OHR.MegellanicCloud_ZH-CN5132305226_1920x1080.jpg&rf=LaDigue_1920x1080.jpg&pid=hp'
INFO: 2020-04-27 11:09:40,773: save_locally() 'Local path: /home/hine/.config/variety/Downloaded/Bing/OHR.MegellanicCloud_ZH-CN5132305226_1920x1080.jpg'
INFO: 2020-04-27 11:09:40,773: save_locally() 'File already exists, skip downloading'
INFO: 2020-04-27 11:12:41,775: get_throttling() 'Bing: parsing serverside options'
INFO: 2020-04-27 11:12:41,776: get_throttling() 'Could not parse Bing serverside options, using defaults None, None'
INFO: 2020-04-27 11:12:41,776: get_throttling() 'Bing: parsing serverside options'
INFO: 2020-04-27 11:12:41,776: get_throttling() 'Could not parse Bing serverside options, using defaults None, None'
INFO: 2020-04-27 11:12:41,776: download_one() 'Bing: Downloading an image, config: None'
INFO: 2020-04-27 11:12:41,776: download_one() 'Bing: Queue size: 4'
INFO: 2020-04-27 11:12:41,776: download_one() 'Bing: Queue populated with 4 URLs'
INFO: 2020-04-27 11:12:41,777: save_locally() 'Origin URL: https://www.bing.com/search?q=%E5%A4%A7%E6%A3%B1%E9%95%9C%E6%B3%89&form=hpcapt&mkt=zh-cn'
INFO: 2020-04-27 11:12:41,777: save_locally() 'Image URL: https://www.bing.com/th?id=OHR.GPS_ZH-CN5160095061_1920x1080.jpg&rf=LaDigue_1920x1080.jpg&pid=hp'
INFO: 2020-04-27 11:12:41,777: save_locally() 'Local path: /home/hine/.config/variety/Downloaded/Bing/OHR.GPS_ZH-CN5160095061_1920x1080.jpg'
INFO: 2020-04-27 11:12:41,777: save_locally() 'File already exists, skip downloading'
INFO: 2020-04-27 11:14:39,051: regular_change_thread() 'regular_change changes wallpaper'
INFO: 2020-04-27 11:14:39,051: set_wallpaper() 'Calling set_wallpaper with /home/hine/.config/variety/Downloaded/Bing/OHR.DrumhellerBadlands_ZH-CN3069391817_1920x1080.jpg'
INFO: 2020-04-27 11:14:39,052: do_set_wp() 'Calling do_set_wp with /home/hine/.config/variety/Downloaded/Bing/OHR.DrumhellerBadlands_ZH-CN3069391817_1920x1080.jpg, time: 1587957279.0524924'
INFO: 2020-04-27 11:14:39,053: prepare_thread() 'Prepared buffer contains 50 images'
INFO: 2020-04-27 11:14:39,065: update_indicator() 'Setting file info to: /home/hine/.config/variety/Downloaded/Bing/OHR.DrumhellerBadlands_ZH-CN3069391817_1920x1080.jpg'
INFO: 2020-04-27 11:14:39,066: list_files() 'More than 1 files in the folders, stop listing'
INFO: 2020-04-27 11:14:41,054: trigger_download() 'Triggering download thread to check if download needed'
INFO: 2020-04-27 11:14:41,055: get_throttling() 'Bing: parsing serverside options'
INFO: 2020-04-27 11:14:41,055: get_throttling() 'Could not parse Bing serverside options, using defaults None, None'
INFO: 2020-04-27 11:14:41,055: get_throttling() 'Bing: parsing serverside options'
INFO: 2020-04-27 11:14:41,056: get_throttling() 'Could not parse Bing serverside options, using defaults None, None'
INFO: 2020-04-27 11:14:41,056: download_one() 'Bing: Downloading an image, config: None'
INFO: 2020-04-27 11:14:41,056: download_one() 'Bing: Queue size: 3'
INFO: 2020-04-27 11:14:41,056: download_one() 'Bing: Queue populated with 3 URLs'
INFO: 2020-04-27 11:14:41,056: save_locally() 'Origin URL: https://www.bing.com/search?q=%E6%80%80%E6%B3%A2%E7%93%A6%E6%A3%AE%E6%9E%97&form=hpcapt&mkt=zh-cn'
INFO: 2020-04-27 11:14:41,057: save_locally() 'Image URL: https://www.bing.com/th?id=OHR.KauriTree_ZH-CN3695568740_1920x1080.jpg&rf=LaDigue_1920x1080.jpg&pid=hp'
INFO: 2020-04-27 11:14:41,057: save_locally() 'Local path: /home/hine/.config/variety/Downloaded/Bing/OHR.KauriTree_ZH-CN3695568740_1920x1080.jpg'
INFO: 2020-04-27 11:14:41,057: save_locally() 'File already exists, skip downloading'
INFO: 2020-04-27 11:17:42,059: get_throttling() 'Bing: parsing serverside options'
INFO: 2020-04-27 11:17:42,059: get_throttling() 'Could not parse Bing serverside options, using defaults None, None'
INFO: 2020-04-27 11:17:42,059: get_throttling() 'Bing: parsing serverside options'
INFO: 2020-04-27 11:17:42,060: get_throttling() 'Could not parse Bing serverside options, using defaults None, None'
INFO: 2020-04-27 11:17:42,060: download_one() 'Bing: Downloading an image, config: None'
INFO: 2020-04-27 11:17:42,060: download_one() 'Bing: Queue size: 2'
INFO: 2020-04-27 11:17:42,060: download_one() 'Bing: Queue populated with 2 URLs'
INFO: 2020-04-27 11:17:42,060: save_locally() 'Origin URL: https://www.bing.com/search?q=%E7%BA%A2%E5%AE%9D%E7%9F%B3%E6%B5%B7%E6%BB%A9&form=hpcapt&mkt=zh-cn'
INFO: 2020-04-27 11:17:42,061: save_locally() 'Image URL: https://www.bing.com/th?id=OHR.RubySunset_ZH-CN5544596519_1920x1080.jpg&rf=LaDigue_1920x1080.jpg&pid=hp'
INFO: 2020-04-27 11:17:42,061: save_locally() 'Local path: /home/hine/.config/variety/Downloaded/Bing/OHR.RubySunset_ZH-CN5544596519_1920x1080.jpg'
INFO: 2020-04-27 11:17:42,061: save_locally() 'File already exists, skip downloading'
INFO: 2020-04-27 11:19:39,294: regular_change_thread() 'regular_change changes wallpaper'
INFO: 2020-04-27 11:19:39,294: set_wallpaper() 'Calling set_wallpaper with /home/hine/.config/variety/Downloaded/Bing/OHR.Knowth_ZH-CN0295374506_1920x1080.jpg'
INFO: 2020-04-27 11:19:39,295: do_set_wp() 'Calling do_set_wp with /home/hine/.config/variety/Downloaded/Bing/OHR.Knowth_ZH-CN0295374506_1920x1080.jpg, time: 1587957579.2952201'
INFO: 2020-04-27 11:19:39,295: prepare_thread() 'Prepared buffer contains 49 images'
INFO: 2020-04-27 11:19:39,312: update_indicator() 'Setting file info to: /home/hine/.config/variety/Downloaded/Bing/OHR.Knowth_ZH-CN0295374506_1920x1080.jpg'
INFO: 2020-04-27 11:19:39,313: list_files() 'More than 1 files in the folders, stop listing'
INFO: 2020-04-27 11:19:41,296: trigger_download() 'Triggering download thread to check if download needed'
INFO: 2020-04-27 11:19:41,300: purge_downloaded() 'Refreshed download folder size: 16.643945693969727 mb'
INFO: 2020-04-27 11:19:41,300: get_throttling() 'Bing: parsing serverside options'
INFO: 2020-04-27 11:19:41,301: get_throttling() 'Could not parse Bing serverside options, using defaults None, None'
INFO: 2020-04-27 11:19:41,301: get_throttling() 'Bing: parsing serverside options'
INFO: 2020-04-27 11:19:41,301: get_throttling() 'Could not parse Bing serverside options, using defaults None, None'
INFO: 2020-04-27 11:19:41,301: download_one() 'Bing: Downloading an image, config: None'
INFO: 2020-04-27 11:19:41,302: download_one() 'Bing: Queue size: 1'
INFO: 2020-04-27 11:19:41,302: download_one() 'Bing: Queue populated with 1 URLs'
INFO: 2020-04-27 11:19:41,303: save_locally() 'Origin URL: https://www.bing.com/search?q=%E8%93%9D%E9%93%83%E8%8A%B1&form=hpcapt&mkt=zh-cn'
INFO: 2020-04-27 11:19:41,303: save_locally() 'Image URL: https://www.bing.com/th?id=OHR.BluebellWood_ZH-CN8128422960_1920x1080.jpg&rf=LaDigue_1920x1080.jpg&pid=hp'
INFO: 2020-04-27 11:19:41,303: save_locally() 'Local path: /home/hine/.config/variety/Downloaded/Bing/OHR.BluebellWood_ZH-CN8128422960_1920x1080.jpg'
INFO: 2020-04-27 11:19:41,303: save_locally() 'File already exists, skip downloading'
INFO: 2020-04-27 11:22:42,307: purge_downloaded() 'Refreshed download folder size: 16.643945693969727 mb'
INFO: 2020-04-27 11:22:42,308: get_throttling() 'Bing: parsing serverside options'
INFO: 2020-04-27 11:22:42,308: get_throttling() 'Could not parse Bing serverside options, using defaults None, None'
INFO: 2020-04-27 11:22:42,308: get_throttling() 'Bing: parsing serverside options'
INFO: 2020-04-27 11:22:42,308: get_throttling() 'Could not parse Bing serverside options, using defaults None, None'
INFO: 2020-04-27 11:22:42,308: download_one() 'Bing: Downloading an image, config: None'
INFO: 2020-04-27 11:22:42,308: download_one() 'Bing: Queue size: 0'
INFO: 2020-04-27 11:22:42,309: get_throttling() 'Bing: parsing serverside options'
INFO: 2020-04-27 11:22:42,309: get_throttling() 'Could not parse Bing serverside options, using defaults None, None'
INFO: 2020-04-27 11:22:42,309: download_one() 'Bing: Filling queue'
ERROR: 2020-04-27 11:22:42,312: download_one_from() 'Could not download wallpaper:'
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/urllib3/connection.py", line 159, in _new_conn
    conn = connection.create_connection(
  File "/usr/lib/python3.8/site-packages/urllib3/util/connection.py", line 61, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "/usr/lib/python3.8/socket.py", line 918, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -2] 未知的名称或服务

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/urllib3/connectionpool.py", line 670, in urlopen
    httplib_response = self._make_request(
  File "/usr/lib/python3.8/site-packages/urllib3/connectionpool.py", line 381, in _make_request
    self._validate_conn(conn)
  File "/usr/lib/python3.8/site-packages/urllib3/connectionpool.py", line 976, in _validate_conn
    conn.connect()
  File "/usr/lib/python3.8/site-packages/urllib3/connection.py", line 308, in connect
    conn = self._new_conn()
  File "/usr/lib/python3.8/site-packages/urllib3/connection.py", line 171, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x7fb67cea53a0>: Failed to establish a new connection: [Errno -2] 未知的名称或服务

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/usr/lib/python3.8/site-packages/urllib3/connectionpool.py", line 724, in urlopen
    retries = retries.increment(
  File "/usr/lib/python3.8/site-packages/urllib3/util/retry.py", line 439, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='www.bing.com', port=443): Max retries exceeded with url: /HPImageArchive.aspx?format=js&idx=0&n=100&mkt=en-US (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fb67cea53a0>: Failed to establish a new connection: [Errno -2] 未知的名称或服务'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/variety/VarietyWindow.py", line 1159, in download_one_from
    file = downloader.download_one()
  File "/usr/lib/python3.8/site-packages/variety/plugins/downloaders/DefaultDownloader.py", line 141, in download_one
    items = self.fill_queue()
  File "/usr/lib/python3.8/site-packages/variety/plugins/builtin/downloaders/BingDownloader.py", line 61, in fill_queue
    s = Util.fetch_json(BingDownloader.BING_JSON_URL)
  File "/usr/lib/python3.8/site-packages/variety/Util.py", line 643, in fetch_json
    return Util.request(url, data, **request_kwargs).json()
  File "/usr/lib/python3.8/site-packages/variety/Util.py", line 612, in request
    r = requests.request(
  File "/usr/lib/python3.8/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python3.8/site-packages/requests/sessions.py", line 530, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3.8/site-packages/requests/sessions.py", line 643, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3.8/site-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='www.bing.com', port=443): Max retries exceeded with url: /HPImageArchive.aspx?format=js&idx=0&n=100&mkt=en-US (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fb67cea53a0>: Failed to establish a new connection: [Errno -2] 未知的名称或服务'))
INFO: 2020-04-27 11:24:39,554: regular_change_thread() 'regular_change changes wallpaper'
INFO: 2020-04-27 11:24:39,554: set_wallpaper() 'Calling set_wallpaper with /home/hine/.config/variety/Downloaded/Bing/OHR.ShyGuy_ZH-CN7391687938_1920x1080.jpg'
INFO: 2020-04-27 11:24:39,555: do_set_wp() 'Calling do_set_wp with /home/hine/.config/variety/Downloaded/Bing/OHR.ShyGuy_ZH-CN7391687938_1920x1080.jpg, time: 1587957879.5552757'
INFO: 2020-04-27 11:24:39,555: prepare_thread() 'Prepared buffer contains 48 images'
INFO: 2020-04-27 11:24:39,572: update_indicator() 'Setting file info to: /home/hine/.config/variety/Downloaded/Bing/OHR.ShyGuy_ZH-CN7391687938_1920x1080.jpg'
INFO: 2020-04-27 11:24:39,573: list_files() 'More than 1 files in the folders, stop listing'
INFO: 2020-04-27 11:24:41,556: trigger_download() 'Triggering download thread to check if download needed'
INFO: 2020-04-27 11:24:41,557: get_throttling() 'Bing: parsing serverside options'
INFO: 2020-04-27 11:24:41,557: get_throttling() 'Could not parse Bing serverside options, using defaults None, None'
INFO: 2020-04-27 11:24:41,557: get_throttling() 'Bing: parsing serverside options'
INFO: 2020-04-27 11:24:41,558: get_throttling() 'Could not parse Bing serverside options, using defaults None, None'
INFO: 2020-04-27 11:24:41,558: download_one() 'Bing: Downloading an image, config: None'
INFO: 2020-04-27 11:24:41,558: download_one() 'Bing: Queue size: 0'
INFO: 2020-04-27 11:24:41,558: get_throttling() 'Bing: parsing serverside options'
INFO: 2020-04-27 11:24:41,558: get_throttling() 'Could not parse Bing serverside options, using defaults None, None'
INFO: 2020-04-27 11:24:41,558: download_one() 'Bing: Filling queue'
INFO: 2020-04-27 11:24:42,023: download_one() 'Bing: Queue populated with 8 URLs'
INFO: 2020-04-27 11:24:42,024: save_locally() 'Origin URL: https://www.bing.com/search?q=%E8%93%9D%E9%93%83%E8%8A%B1&form=hpcapt&mkt=zh-cn'
INFO: 2020-04-27 11:24:42,024: save_locally() 'Image URL: https://www.bing.com/th?id=OHR.BluebellWood_ZH-CN8128422960_1920x1080.jpg&rf=LaDigue_1920x1080.jpg&pid=hp'
INFO: 2020-04-27 11:24:42,024: save_locally() 'Local path: /home/hine/.config/variety/Downloaded/Bing/OHR.BluebellWood_ZH-CN8128422960_1920x1080.jpg'
INFO: 2020-04-27 11:24:42,024: save_locally() 'File already exists, skip downloading'
INFO: 2020-04-27 11:27:43,026: get_throttling() 'Bing: parsing serverside options'
INFO: 2020-04-27 11:27:43,026: get_throttling() 'Could not parse Bing serverside options, using defaults None, None'
INFO: 2020-04-27 11:27:43,026: get_throttling() 'Bing: parsing serverside options'
INFO: 2020-04-27 11:27:43,026: get_throttling() 'Could not parse Bing serverside options, using defaults None, None'
INFO: 2020-04-27 11:27:43,027: download_one() 'Bing: Downloading an image, config: None'
INFO: 2020-04-27 11:27:43,027: download_one() 'Bing: Queue size: 7'
INFO: 2020-04-27 11:27:43,027: download_one() 'Bing: Queue populated with 7 URLs'
INFO: 2020-04-27 11:27:43,027: save_locally() 'Origin URL: https://www.bing.com/search?q=%E7%BA%A2%E5%AE%9D%E7%9F%B3%E6%B5%B7%E6%BB%A9&form=hpcapt&mkt=zh-cn'
INFO: 2020-04-27 11:27:43,028: save_locally() 'Image URL: https://www.bing.com/th?id=OHR.RubySunset_ZH-CN5544596519_1920x1080.jpg&rf=LaDigue_1920x1080.jpg&pid=hp'
INFO: 2020-04-27 11:27:43,028: save_locally() 'Local path: /home/hine/.config/variety/Downloaded/Bing/OHR.RubySunset_ZH-CN5544596519_1920x1080.jpg'
INFO: 2020-04-27 11:27:43,028: save_locally() 'File already exists, skip downloading'
INFO: 2020-04-27 11:29:39,789: regular_change_thread() 'regular_change changes wallpaper'
INFO: 2020-04-27 11:29:39,790: set_wallpaper() 'Calling set_wallpaper with /home/hine/.config/variety/Downloaded/Bing/OHR.FormentorHolidays_ZH-CN3392936755_1920x1080.jpg'
INFO: 2020-04-27 11:29:39,790: prepare_thread() 'Prepared buffer contains 47 images'
INFO: 2020-04-27 11:29:39,791: do_set_wp() 'Calling do_set_wp with /home/hine/.config/variety/Downloaded/Bing/OHR.FormentorHolidays_ZH-CN3392936755_1920x1080.jpg, time: 1587958179.7911515'
INFO: 2020-04-27 11:29:39,806: update_indicator() 'Setting file info to: /home/hine/.config/variety/Downloaded/Bing/OHR.FormentorHolidays_ZH-CN3392936755_1920x1080.jpg'
INFO: 2020-04-27 11:29:39,807: list_files() 'More than 1 files in the folders, stop listing'
INFO: 2020-04-27 11:29:41,792: trigger_download() 'Triggering download thread to check if download needed'
INFO: 2020-04-27 11:29:41,793: get_throttling() 'Bing: parsing serverside options'
INFO: 2020-04-27 11:29:41,793: get_throttling() 'Could not parse Bing serverside options, using defaults None, None'
INFO: 2020-04-27 11:29:41,793: get_throttling() 'Bing: parsing serverside options'
INFO: 2020-04-27 11:29:41,793: get_throttling() 'Could not parse Bing serverside options, using defaults None, None'
INFO: 2020-04-27 11:29:41,793: download_one() 'Bing: Downloading an image, config: None'
INFO: 2020-04-27 11:29:41,794: download_one() 'Bing: Queue size: 6'
INFO: 2020-04-27 11:29:41,794: download_one() 'Bing: Queue populated with 6 URLs'
INFO: 2020-04-27 11:29:41,794: save_locally() 'Origin URL: https://www.bing.com/search?q=%E6%80%80%E6%B3%A2%E7%93%A6%E6%A3%AE%E6%9E%97&form=hpcapt&mkt=zh-cn'
INFO: 2020-04-27 11:29:41,794: save_locally() 'Image URL: https://www.bing.com/th?id=OHR.KauriTree_ZH-CN3695568740_1920x1080.jpg&rf=LaDigue_1920x1080.jpg&pid=hp'
INFO: 2020-04-27 11:29:41,794: save_locally() 'Local path: /home/hine/.config/variety/Downloaded/Bing/OHR.KauriTree_ZH-CN3695568740_1920x1080.jpg'
INFO: 2020-04-27 11:29:41,795: save_locally() 'File already exists, skip downloading'
